### ISSUE TITLE
App Deatils: categories not shown.

### ISSUE THREAD

**Issue by pcampanella** [wasdi-cloud/wasdiClient2#103]
The app details page does not show the categories associated to an app:
![image](https://github.com/wasdi-cloud/wasdiClient2/assets/6428249/dd06bd38-141b-42ad-84a0-c6f7c388108e)

Is written but are not listed !

**Comment by bspurgeon08** [comment]
@pcampanella when I re-work the app details page with the new design, I will add it then! :)
