### ISSUE TITLE
OLD CLIENT (but critical): app store -> run app providing the name of the WS. Browser crash

### ISSUE THREAD

**Issue by pcampanella** [wasdi-cloud/wasdiClient2#110]
If you try to give the name of the workspace when running an app, it looks the browser crash.
Is the old client but too critical, must be solved.

**Comment by mmenapace** [comment]
Made a first test with the current setup:
- Locally deployed webpacked version, Using VScode Live Server 
- BE from test.wasdi.net
- RabbitMQ non connected 
- Chrome 120.0.6099.225 

Lanched an application and changed WS name 
Tested several times -> No Browser crash

**Comment by mmenapace** [comment]
Locally deployed webpacked version, Using VScode Live Server
BE from test.wasdi.net
RabbitMQ non connected
Firefox 122
Lanched an application and changed WS name
Tested several times -> Managed to crash 
Working to find a consistent way to reproducible behaviour

**Comment by mmenapace** [comment]
Found the issue: in the link from wasdi.cloud webpage target="_blank" is specified.
This lead the browser to think that the passage to the editor represents a pop up and suppress it. 
Removing the target="_blank" from the original webpage solve the issue. 
Working on solution leveraging on JQuery for Hubspot side

**Comment by mmenapace** [comment]
Fixed by levaraging to footer script in hubspot advanced settigns 
![image](https://github.com/wasdi-cloud/wasdiClient2/assets/26542988/0674ee80-2a03-47cc-8db1-7de18ec52b4c)
