### ISSUE TITLE
Apps UI -> glitch on the layer button

### ISSUE THREAD

**Issue by kr1zz** [wasdi-cloud/wasdiClient2#111]
Hover on the layers selector in the top right part of any map in the apps UI, and it turns into a smaller empty rectangle

![image](https://github.com/wasdi-cloud/wasdiClient2/assets/2588293/dc231714-1e31-4dad-98cb-42d91a5906fe)
![image](https://github.com/wasdi-cloud/wasdiClient2/assets/2588293/048c0b28-6145-4e8b-8bca-94364cae46b5)

**Comment by bspurgeon08** [comment]
@kr1zz just to update you here - I am going to start working on the search page, so I will do this issue in conjunction with that. Sorry if it's disrupting your workflow at the moment!

Thanks for waiting :)
