### ISSUE TITLE
Documentation icon missing in the marketplace (bottom left)

### ISSUE THREAD

**Issue by kr1zz** [wasdi-cloud/wasdiClient2#118]
Marketplace:
![image](https://github.com/wasdi-cloud/wasdiClient2/assets/2588293/0dffc6f9-ac55-4635-a4fe-2e6c618c3023)

Workspaces (but any other screen has it):
![image](https://github.com/wasdi-cloud/wasdiClient2/assets/2588293/1527bf43-9402-4c56-a312-1832eb4d89a8)

Add the help icon in the marketplace

**Comment by bspurgeon08** [comment]
For this, you just need to scroll to the bottom in the Marketplace. 

The documentation icon is just at the bottom of the view port - like a footer
