### ISSUE TITLE
Cannot read product names in workspace

### ISSUE THREAD

**Issue by kr1zz** [wasdi-cloud/wasdiClient2#134]
New:
![image](https://github.com/wasdi-cloud/wasdiClient2/assets/2588293/3df30eba-977d-4a56-8fac-f0d7139a9ef1)
Old:
![image](https://github.com/wasdi-cloud/wasdiClient2/assets/2588293/a98da126-d347-41c8-870d-674866b08dc5)

There is not enough room to show the names of the products

**Comment by pcampanella** [comment]
At the moment here, in the editor, there is the horizontal scroll bar.
In theory this is already the result of a negotiation.
We will see.
