### ISSUE TITLE
Download Shape File: I got only the shp

### ISSUE THREAD

**Issue by pcampanella** [wasdi-cloud/wasdiClient2#160]
The download of shape files should zip all the related files.
I made one test in the new client in CharterKeniaApril2024 workspace and I got only shp.
We need to check if it was a problem of that file or it is a problem of the new client or a regression on the server.

**Comment by leonevalentina** [comment]
I checked the code starting from the endpoint `/catalog/downloadbyname` and, from there, it looks like the case of shape files should be handled correctly. The execution should end up in the method `CatalogResources.zipShapeFile`. 

I just don't know how to reproduce the bug. @pcampanella , do we have some data provider which returns a shape file? Or can you maybe share the workspace and tell me the product which is giving you this issue? I can try to check server side

**Comment by pcampanella** [comment]
I tested: I uploaded a shape file in a workspace (as zip, with all the subfiles).
WASDI ingested it correctly.
I downloaded from new client -> only shp
I downloaded from the old client -> a zip file with all.

So there must be something different in the call we make.

**Comment by bspurgeon08** [comment]
I'm looking into this and the .zip files that I tried were received as zip files.

Can you share the file you used to test with me?
