### ISSUE TITLE
Workspace page: cannot visualize the metadata of a product

### ISSUE THREAD

**Issue by leonevalentina** [wasdi-cloud/wasdiClient2#163]
I cannot visualize the metadata of a product when I click on the "Metadata" label.
It works on the old client, though, and I can expand the list of metadata by clicking on the small arrow on the left of the icon.

![image](https://github.com/wasdi-cloud/wasdiClient2/assets/135051102/637e57fa-29d0-4f26-9460-7a3076a53d5f)

On the same product, on the new client, I cannot visualize the same list:
![image](https://github.com/wasdi-cloud/wasdiClient2/assets/135051102/d20646bf-bdc3-46aa-bdee-257b3f82af7b)

To reproduce, you can try to import a S3 product in your workspace. S3 products usually have readable metadata.

**Comment by pcampanella** [comment]
I tested also this and I'm not convinced yet. 
Now by default we do not produce metadata anymore. Metadata is produced "on demand". 
The demand is when the user clicks on metadata of a product.
The old client check if the metadata is available (already "created") or not. If not trigger the execution of an operation on the launcher to read metadata that, later, can be read.
I tried a couple of product with the new client and I always received "not available". So I'm not sure.
