### ISSUE TITLE
Search -> Add to workspace, different problems

### ISSUE THREAD

**Issue by pcampanella** [wasdi-cloud/wasdiClient2#168]
In the search and then add to workspace I found 2 problems:

1) If I have an open workspace, this is supposed to be pre-selected when I click to add to workspace. At the moment is not:
![image](https://github.com/wasdi-cloud/wasdiClient2/assets/6428249/46eac1ea-d6f4-4797-a5ea-b1f2d576fbd6)

I had to reselect it every time.

2) If I select more than one product, and I use the button add to workspace on the top of the list, again the active workspace is not selected but, worst, I was not able to make the import start. It worked only one by one. Instead if there are more products selected should request the download of all (I do not remember the old client, or it was a dedicated api or simply call the download api for all the selected products).

**Comment by pcampanella** [comment]
The first part is ok.
But when I tried to add 2 products with one click, the send to workspace dialog did not closed and the downloads did not start.

**Comment by pcampanella** [comment]
I'm sorry @bspurgeon08  but the second part still does not work for me.
Maybe we are doing different things?
We should take a quick look together

**Comment by bspurgeon08** [comment]
I noticed the problem was if the product type did not have a bounds value - I've added the check, so I think this should solve the issue (?) adding to TEST again
