### ISSUE TITLE
Workspaces: cannot go back to initial view

### ISSUE THREAD

**Issue by kr1zz** [wasdi-cloud/wasdiClient2#188]
How can a user go back to the original compact view:
![image](https://github.com/user-attachments/assets/48fb957e-2d39-4534-94c4-6bad56fc4126)
from the extended list view?
![image](https://github.com/user-attachments/assets/0e47ec88-1849-4998-81be-2d0e7c02a5ce)

There's no button/link, and clicking again on the workspace icon does not switch to the previous visualization. Hitting the back button on the browser does not work either (it goes back to the previous page, e.g. the marketplace)

Maybe it's not really a bug, but it's annoying in these two scenarios:
1. the user hits the >< symbol by mistake
2. the user wants to see the list of workspaces to decide if they neeed to create a new one

**Comment by bspurgeon08** [comment]
The user just has to click the same symbol the collapse the extended list

**Comment by pcampanella** [comment]
I also use the same button, and it looks it works. No?

**Comment by bspurgeon08** [comment]
@pcampanella - it works, but Cri and I landed on a solution where the button stays highlighted when opened so it's more obvious where it is. Once re-built, let me know what you think
