### ISSUE TITLE
Importing data should read FETCH instead of DOWNLOAD

### ISSUE THREAD

**Issue by kr1zz** [wasdi-cloud/wasdiClient2#192]
Replace "DOWNLOAD" with "FETCH" in the progress bar
![image](https://github.com/user-attachments/assets/dce6c36b-529a-4eb9-8438-46e9e692a57b)

**Comment by jihed-Sh** [comment]
I just fixed it and it is ready to reviewed

**Comment by jihed-Sh** [comment]
PS: this is not the ideal solution , since we're altering information from the server.

**Comment by pcampanella** [comment]
No this did not work!
At the moment the filter is not working anymore.

I suggest to QUICKLY revert to DOWNLOAD.

The fetch was in the old client, was only a tranlation local. But I think we can live without.

**Comment by jihed-Sh** [comment]
working on it

**Comment by jihed-Sh** [comment]
fixed :)
