### ISSUE TITLE
Import Windows: does it closes automatically?

### ISSUE THREAD

**Issue by pcampanella** [wasdi-cloud/wasdiClient2#194]
I imported a quite big file in a workspace.
The dialog did not closed.
Maybe it was waiting for the upload to finish, I do not know, must be verified.
But still the impression was of something not working..
Maybe we can just close it after the click on import
Or if this is not the case, we can disable the button and the area for drag and drop until the upload is not done and the dialog closed. 
Verify also if there is already a notification something like "your upload started"..

**Comment by bspurgeon08** [comment]
@jihed-Sh will take on this one and he will add a disabled state to the drag and drop

**Comment by jihed-Sh** [comment]
done ! added a spinner and disabled the button until the upload operation is done

**Comment by pcampanella** [comment]
ok I can close this but can you change the spinner with the WASDI spinner (Alien) ? @bspurgeon08  can show how!
