### ISSUE TITLE
Process Workspace History (both, last 5 and the full view): missing the processes

### ISSUE THREAD

**Issue by pcampanella** [wasdi-cloud/wasdiClient2#22]
The list of processes must have some problem. To reproduce:
.Login in test as me with the old client
.open Main Workspace
Do the same in the new client.
You will see that the list of processes is completly different.
Is there any strange filter?

**Comment by bspurgeon08** [comment]
To confirm, this is upon opening the Processes Bar once inside a workspace? 

Because if so: for me when I reproduce this issue, I actually get the same processes list, but my OPERATION is different. 
I need to make RUNPROCESSOR -> APP, but otherwise I do not see a difference.

**Comment by pcampanella** [comment]
First of all for the RUNPROCESSOR -> APP you are also right. In the old client there was a mapping between WASDI Operation names and what to show in the client. 
For the list now I agree with you.
Or it was a special condition I cannot reproduce now, or something new in the version I do not know.
