### ISSUE TITLE
Client tab Title (from index ?!)

### ISSUE THREAD

**Issue by pcampanella** [wasdi-cloud/wasdiClient2#23]
The title of the tab in chrome is now "Client".
Change it in WASDI.
As the old client, when the user open a workspace, change the title with the name of the active workspace.

**Comment by pcampanella** [comment]
Ok good. Please add:
1. favicon -> use the WASDI Logo
2. Keep always the text Wasdi 2.0 and just ADD a "- [wsname]" when there is a ws open.

**Comment by bspurgeon08** [comment]
When testing: Empty Cache and Hard Reload to clear the old favicon :)
