### ISSUE TITLE
Search results: missing back button

### ISSUE THREAD

**Issue by pcampanella** [wasdi-cloud/wasdiClient2#29]
When a user makes a search wasdi shows the results tab.
Add a button to come back to the search filters. This button as in the old client should keep the filters that was selected by the user.

**Comment by pcampanella** [comment]
Now is much better.
But there is another bug.
Ok to keep the bbox and files when the user goes back.
BUT the footprints on the map MUST BE CLEANED after each search click.
Now is "cumulating" many footprints of different searches.

**Comment by bspurgeon08** [comment]
I cannot re-create this bug at the moment. 

When I execute the search (in testnew) the footprints are cleared when I execute the subsequent search.
