### ISSUE TITLE
Pre-fill Open Workspace with current workspace

### ISSUE THREAD

**Issue by bspurgeon08** [wasdi-cloud/wasdiClient2#74]
In the App UI page:

- If the user has an open workspace, the user should see that workspace as the default value for the Open Workspace dropdown, rather than the text "Open Workspace"

**Comment by pcampanella** [comment]
This now works but is not clear to me what happens.
Ok is preselected. But in the old client there was an explicit choice new or existing.
By default new selected, and if there is a workspace open AND the user select existing, the open one was pre-selected.
But is a kind of 2 step.
Now I see a text box for new ws and a combo for existing, but is not clear to me at least if I click run if it goes in a new one or in the existing.
I hope I was able to exaplain myself :)

**Comment by bspurgeon08** [comment]
@pcampanella I re-implemented the two step selection instead of the two side-by-side inputs. We might change this again, but it did make more sense to do it this way. 

Please let me know if there are any new problems with it.
