### ISSUE TITLE
Remove label "shared with" when the workspace is not shared with anyone

### ISSUE THREAD

**Issue by leonevalentina** [wasdi-cloud/wasdiClient2#78]
Hi Betty, 

When we display the properties of a workspace, I think it would be better to remove the label "shared with: ", when the workspace is not shared. I think it could be misleading for the user to see first that label, and immediately below the list of products of the workspace.

Let me know what do you think.

**How to reproduce:**

From the page where we display the list of workspaces, click on a workspace that is not shared with other people to see its properties. You will notice the label with an empty value.

![ws_new_client](https://github.com/wasdi-cloud/wasdiClient2/assets/135051102/0cf6bf51-08b3-47a3-9f93-a05756732e52)

In the old client, instead, the label is not shown when the workspace is not shared.
![ws_old_client](https://github.com/wasdi-cloud/wasdiClient2/assets/135051102/2c742548-7a47-42a2-8950-89774d320f72)

**Comment by pcampanella** [comment]
I do not see this solved yet:



![Image](https://github.com/wasdi-cloud/wasdiClient2/assets/6428249/8f4acad3-904b-4c49-9459-a9f7d2428098)
