### ISSUE TITLE
Editor: Add Option to have email notification at the end of a process

### ISSUE THREAD

**Issue by bspurgeon08** [wasdi-cloud/wasdiClient2#82]
Originally published as [Issue #385](https://github.com/fadeoutsoftware/WASDI/issues/385) by Paolo in the old client. 

The user shall be able to tick an option to be notified by mail at the end of an app started.

**Commented 21/10/2022**
Here we should work on different aspects. We must decide how to offer this possibility. I think in the client we must support it both in the "technical" apps view and in the marketplace. Should be like a checkbox "notify me on end".
On the server side we need to receive also this flag.
On the launcher use it to send mail (and decide how to send mail in the launcher).
Lets all work on this task in a separate branch.

**Commented 08/12/2024**
This is in my very long wish list.
For sure in the new client I would like to have it.
I think we can add:
.Checkboxes on the client to request this mail
.In the ProcessorResource, method internalRun add a flag to send the mail, false by default
.Reflect this change in the API (I think run and runPost in the same resource) so that we can receive this flag from the client
.Extend the ProcessorParameter with this flag, false by default
.In the Runprocessor operation in the launcher, we will receive the parameter: change the method from this
// Execute User Processor
ProcessorParameter oParameter = (ProcessorParameter) oParam;
WasdiProcessorEngine oEngine = WasdiProcessorEngine.getProcessorEngine(oParameter.getProcessorType());
oEngine.setSendToRabbit(m_oSendToRabbit);
oEngine.setParameter(oParameter);
oEngine.setProcessWorkspaceLogger(m_oProcessWorkspaceLogger);
oEngine.setProcessWorkspace(oProcessWorkspace);
return oEngine.run(oParameter);
To something like this:
// Execute User Processor
ProcessorParameter oParameter = (ProcessorParameter) oParam;
WasdiProcessorEngine oEngine = WasdiProcessorEngine.getProcessorEngine(oParameter.getProcessorType());
oEngine.setSendToRabbit(m_oSendToRabbit);
oEngine.setParameter(oParameter);
oEngine.setProcessWorkspaceLogger(m_oProcessWorkspaceLogger);
oEngine.setProcessWorkspace(oProcessWorkspace);
boolean bRun = oEngine.run(oParameter);
if (oParamters.NEWFLAGSENDMAIL){
TODO SEND MAIL
}
return bRun

To send the mail at the moment we have Mercurius. One day we should change.
It is wrapped in the WasdiResource.sendEmail static method.
I saw no problem to move this method in shared so that can be used by the other components.

**Comment by pcampanella** [comment]
BIG UPDATE:
On the server side is done.
We need to support it in the new client.
We need just to add an option both in the marketplace and in the tech apps view.

In the /processors/run API (both POST and GET) we added 
notify
Query Param.
If DOES NOT EXIST => false
Otherwise something like
&notify=true
To request WASDI to send the mail at the end.
