### ISSUE TITLE
Marketplace, Processes Bar, Tech App View: Application Names

### ISSUE THREAD

**Issue by bspurgeon08** [wasdi-cloud/wasdiClient2#83]
Originally published as [Issue #391](https://github.com/fadeoutsoftware/WASDI/issues/391) by Paolo in the old client.

Applications has now 2 names:

- The official "name" that is a code and is at the end the name of the docker.

- The friendly name, can be set by the user.

- Now there is a mix.. we should always use friendly name. If this is null => official name.

- This in the store, in processing bar and dialog, in the tech app view etc.

**Comment by jihed-Sh** [comment]
After discussing this issue with Paolo , it will be divided into other issues and for now we will close it by showing friendly name in the product list
