### ISSUE TITLE
Workspaces: Details - Timestamps and Shared With

### ISSUE THREAD

**Issue by bspurgeon08** [wasdi-cloud/wasdiClient2#90]
The Workspace details in the Workspaces Tab - the timestamps are not formatted and the workspace "shared with" should not appear if there is no shared users.

**Comment by leonevalentina** [comment]
Hi Betty, 
About the Workspace details window, I would like to add a suggestion. 
I noticed that, in the dropdown menu used to change the node of the workspace, nothing is selected. 

I think it would be nice to pre-select the current node of the workspace, as it is done in the current client.

**Comment by bspurgeon08** [comment]
@leonevalentina Ah good catch! Thanks :)

**Comment by pcampanella** [comment]
I still see problems in this: The node is still not pre-selected in the combo!
