### ISSUE TITLE
Processor Log Dialog: finalize pagination

### ISSUE THREAD

**Issue by pcampanella** [wasdi-cloud/wasdiClient2#93]
The processor logs dialog has only the buttons to go to prev or next page.
We should implement a full navigation control including:

last next  prev first  + buttons with the number of pages (with a kind of mobile window limit if they are too much)
Sample:

<< < 10 9 8 7 ... > >>

In the old client:
![image](https://github.com/wasdi-cloud/wasdiClient2/assets/6428249/43e69ea4-29f0-40e3-a8db-1e5e3c5b66e0)

NOTE: Maybe this can be a resusable component!?!?!
We have pagination in many other dialogs or view...

**Comment by bspurgeon08** [comment]
RE - Reusable component. ABSOLUTELY. 

I was looking at the other paginated components and they actually aren't standardized in the current client. I messaged you on discord about Storybook as per Carlo's recommendation. Let me know :)
